### PR TITLE
latexify math expression in README.md

### PR DESCRIPTION
**Pull request by jbytecode**
Due to the JOSS submission: https://github.com/openjournals/joss-reviews/issues/4736

### CODE REVIEW

**Comment by jbytecode** [comment]
@tmigot - I have just realized that the online github editor shows the equation correctly but the produced README.md file is not rendered. You can omit merging this pull request. sorry for the inconvenience.

**Comment by tmigot** [comment]
I was going to say the same when looking at https://github.com/jbytecode/PDENLPModels.jl
, thanks though for trying.

**Comment by tmigot** [comment]
Those equations used to be well rendered, I think something changed recently with Github

**Comment by jbytecode** [comment]
okay, we can leave them as they are, then.

**Comment by tmigot** [comment]
Ok, so I will make a new release then.

**Comment by jbytecode** [comment]
yes, please follow the instruction provided in the main review thread and ping me when you've done with them.

**Pull request closed without merging**
