### PR TITLE
use strict=true in docs

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
Why is this being merged? There are errors in the docs build, which is why I activated `strict=true`:
```
┌ Error: 10 docstrings not included in the manual:
│ 
│     PDENLPModels._split_vectors :: Tuple{AbstractVector, Gridap.FESpaces.FESpace, Gridap.FESpaces.FESpace}
│     PDENLPModels._compute_hess_k_vals!
│     PDENLPModels.PDENLPMeta
│     PDENLPModels._compute_gradient!
│     PDENLPModels._obj_integral
│     PDENLPModels._split_vector :: Tuple{AbstractVector, Gridap.FESpaces.FESpace, Gridap.FESpaces.FESpace}
│     PDENLPModels._split_FEFunction :: Tuple{AbstractVector, Gridap.FESpaces.FESpace, Gridap.FESpaces.FESpace}
│     PDENLPModels._compute_gradient_k!
│     PDENLPModels._compute_hess_structure :: Tuple{AbstractEnergyTerm, Any, Any, Any, Any}
│     PDENLPModels._functions_to_vectors! :: Tuple{Integer, Integer, Gridap.Geometry.Triangulation, Function, Function, Any, Gridap.FESpaces.FESpace, AbstractVector, AbstractVector}
│ 
│ These are docstrings in the checked modules (configured with the modules keyword)
│ that are not included in @docs or @autodocs blocks.
```

**Comment by tmigot** [comment]
It has been merge via https://github.com/JuliaSmoothOptimizers/PDENLPModels.jl/pull/63

**Comment by dpo** [comment]
The objective was to document everything...

**Comment by tmigot** [comment]
That's what I did. For some reason, I couldn't modify this branch directly. So, I opened another PR on top of this one fixing the issue.

**Pull request merged**
